<?php
$expenses=$db->fetchAll("SELECT expense_date,category,responsibility,actual_amount,gst_amount FROM outside_car_expenses WHERE business_id=? AND car_id=? AND status='POSTED' ORDER BY expense_date,created_at",[$businessId,$carId]);
$payments=$db->fetchAll("SELECT payment_date,payment_kind,amount FROM outside_car_buyer_payments WHERE business_id=? AND car_id=? AND status='POSTED' ORDER BY payment_date,created_at",[$businessId,$carId]);
$movements=$db->fetchAll("SELECT movement_date,movement_kind,amount,payable_applied,advance_created,advance_refunded,allocated_amount FROM outside_source_movements WHERE business_id=? AND origin_car_id=? AND status='POSTED' ORDER BY movement_date,created_at",[$businessId,$carId]);
?>
<div class="page-header no-print"><div><h1>Outside Car Commission Statement</h1><p class="page-subtitle">Traditional printable layout with correct commission-agency accounting labels.</p></div><div><button class="btn btn-primary" onclick="printPage()"><i class="ri-printer-line"></i> Print</button> <a href="view.php?id=<?= urlencode($carId) ?>" class="btn btn-outline">Back</a></div></div>
<div class="traditional-deal-sheet">
<header><div><h2><?= clean(formatRegistrationNo($car['registration_no'])) ?></h2><p><?= clean(trim($car['make'].' '.$car['model'])) ?> · <?= clean($car['year']) ?> · <?= clean($car['color']) ?></p></div><div><b>Source Entity</b><br><?= clean($car['source_entity_name']) ?><br><?= clean($car['source_phone']) ?></div></header>
<div class="deal-two-col"><section><h3>Vehicle &amp; Commission</h3><dl><dt>Received</dt><dd><?= formatDate($car['purchase_date']) ?></dd><dt>C: Final Customer Vehicle Price</dt><dd><?= $sale?formatAmount($sale['net_vehicle_value']):'Pending' ?></dd><dt>K: Tiranga Commission (included in C)</dt><dd><?= $sale?formatAmount($sale['separate_commission']):($car['commission_type']==='PERCENT'?clean($car['commission_value']).'%':formatAmount($car['commission_value'])) ?></dd><dt>Source Entity Entitlement (C − K)</dt><dd><?= $sale?formatAmount($sale['source_entity_entitlement']):'Pending' ?></dd><dt>Buyer RTO Charge</dt><dd><?= formatAmount($sale['buyer_rto_charge']??0) ?></dd><dt>Buyer Total</dt><dd><?= formatAmount($sale['buyer_total']??0) ?></dd></dl>
<h3>Expense Detail</h3><table><thead><tr><th>Date</th><th>Expense</th><th>Bearer</th><th>GST</th><th>Amount</th></tr></thead><tbody><?php foreach($expenses as $e): ?><tr><td><?= formatDate($e['expense_date']) ?></td><td><?= clean($e['category']) ?></td><td><?= clean(str_replace('_',' ',$e['responsibility'])) ?></td><td><?= formatAmount($e['gst_amount']) ?></td><td><?= formatAmount($e['actual_amount']) ?></td></tr><?php endforeach; ?><tr class="total"><td colspan="4">Total</td><td><?= formatAmount($f['expense']['actual']??0) ?></td></tr></tbody></table></section>
<section><h3>Buyer Account</h3><?php if($sale): ?><dl><dt>Buyer</dt><dd><?= clean($sale['buyer_name']) ?></dd><dt>Token Applied</dt><dd><?= formatAmount($sale['token_applied']) ?></dd><dt>Received at Sale</dt><dd><?= formatAmount($sale['received_at_sale']) ?></dd><?php foreach($payments as $p): ?><dt><?= clean(($p['payment_kind']??'RECEIPT')==='REFUND'?'Refund':'Installment') ?> · <?= formatDate($p['payment_date']) ?></dt><dd><?= formatAmount($p['amount']) ?></dd><?php endforeach; ?><dt>Collected</dt><dd><?= formatAmount($f['buyer_collected']) ?></dd><dt>Outstanding</dt><dd><?= formatAmount($sale['buyer_outstanding']) ?></dd></dl><?php else: ?><p>Sale not recorded.</p><?php endif; ?>
<h3>Source Entity Account</h3><dl><dt>This Car Entitlement</dt><dd><?= formatAmount($f['source_car_position']['entitlement']) ?></dd><dt>Total Entity Payable</dt><dd><?= formatAmount($f['source_entity_position']['payable']) ?></dd><dt>Recoverable Source Advance</dt><dd><?= formatAmount($f['source_entity_position']['advance']) ?></dd><dt>Tiranga Funds Deployed</dt><dd><?= formatAmount($f['funds_deployed']) ?></dd><dt>RTO Income</dt><dd><?= formatAmount($f['rto_income']) ?></dd><dt>RTO Expense</dt><dd><?= formatAmount($f['rto_expense']) ?></dd><dt>RTO Net</dt><dd><?= formatAmount($f['rto_net']) ?></dd></dl>
<table><thead><tr><th>Date</th><th>Source Movement</th><th>Amount</th><th>Advance Balance</th></tr></thead><tbody><?php foreach($movements as $m): ?><tr><td><?= formatDate($m['movement_date']) ?></td><td><?= clean(str_replace('_',' ',$m['movement_kind'])) ?></td><td><?= formatAmount($m['amount']) ?></td><td><?= formatAmount($m['advance_created']-$m['advance_refunded']-$m['allocated_amount']) ?></td></tr><?php endforeach; ?></tbody></table></section></div>
<footer><div>Source Entity Signature</div><div>Tiranga Authorized Signatory</div><div>Buyer Signature</div></footer></div>
