<?php
$pageTitle='Loan Commissions';$pageIcon='<i class="ri-bank-card-line"></i>';
require_once __DIR__.'/../includes/header.php';require_once __DIR__.'/../includes/accounting_engine.php';
Auth::requireBookAccess('car_profitability','read');$businessId=Auth::user('business_id');new AccountingEngine($businessId,Auth::user('user_id'));
$q=trim((string)get('q',''));$status=strtoupper(trim((string)get('status','')));$from=trim((string)get('from_date',''));$to=trim((string)get('to_date',''));
$where='clc.business_id=?';$params=[$businessId];
if($q!==''){$where.=' AND (c.registration_no LIKE ? OR buyer.name LIKE ? OR financier.name LIKE ? OR clc.loan_account_no LIKE ?)';$like='%'.$q.'%';array_push($params,$like,$like,$like,$like);}
if(in_array($status,['PENDING','PARTIAL','RECEIVED','REVERSED'],true)){$where.=' AND clc.status=?';$params[]=$status;}
if($from!==''){$where.=' AND clc.approval_date>=?';$params[]=$from;}if($to!==''){$where.=' AND clc.approval_date<=?';$params[]=$to;}
$rows=$db->fetchAll("SELECT clc.*,c.registration_no,c.ownership_type,buyer.name buyer_name,financier.name financier_name,je.reference_no FROM car_loan_commissions clc JOIN cars c ON c.id=clc.car_id AND c.business_id=clc.business_id JOIN debtors_creditors buyer ON buyer.id=clc.buyer_party_id JOIN debtors_creditors financier ON financier.id=clc.financier_party_id LEFT JOIN journal_entries je ON je.id=clc.accrual_entry_id WHERE {$where} ORDER BY clc.approval_date DESC,clc.created_at DESC",$params);
$earned=array_sum(array_map(fn($r)=>$r['status']==='REVERSED'?0:floatval($r['commission_amount']),$rows));$received=array_sum(array_map(fn($r)=>$r['status']==='REVERSED'?0:floatval($r['received_amount']),$rows));
?>
<div class="page-header"><div><h1><i class="ri-bank-card-line"></i> Car Loan Commissions</h1><p class="page-subtitle">Customer loan principals are tracking values. Only finance-company commission enters income.</p></div><button onclick="printPage()" class="btn btn-outline"><i class="ri-printer-line"></i> Print</button></div>
<div class="filter-bar"><form method="get"><div><label class="form-label">Car, buyer or finance company</label><input type="search" name="q" class="form-control" value="<?= clean($q) ?>" placeholder="Registration, buyer, financier, file no."></div><div><label class="form-label">Status</label><select name="status" class="form-control"><option value="">All statuses</option><?php foreach(['PENDING','PARTIAL','RECEIVED','REVERSED'] as $value): ?><option value="<?= $value ?>" <?= $status===$value?'selected':'' ?>><?= clean(ucwords(strtolower($value))) ?></option><?php endforeach; ?></select></div><div><label class="form-label">From</label><input type="date" name="from_date" class="form-control" value="<?= clean($from) ?>"></div><div><label class="form-label">To</label><input type="date" name="to_date" class="form-control" value="<?= clean($to) ?>"></div><button class="btn btn-outline btn-sm"><i class="ri-filter-line"></i> Apply</button><?php if($q!==''||$status!==''||$from!==''||$to!==''): ?><a href="loan_commissions.php" class="btn btn-ghost btn-sm">Clear all</a><?php endif; ?></form></div>
<div class="stats-grid"><div class="stat-card"><div class="stat-value"><?= count($rows) ?></div><div class="stat-label">Matching Cases</div></div><div class="stat-card"><div class="stat-value flow-in"><?= formatAmount($earned) ?></div><div class="stat-label">Commission Earned</div></div><div class="stat-card"><div class="stat-value"><?= formatAmount($received) ?></div><div class="stat-label">Received</div></div><div class="stat-card"><div class="stat-value flow-out"><?= formatAmount(max(0,$earned-$received)) ?></div><div class="stat-label">Pending</div></div></div>
<div class="table-container table-container-fill"><table><thead><tr><th>Date</th><th>Car / Buyer</th><th>Finance Company / File</th><th class="text-right">Customer Loan</th><th class="text-right">Commission</th><th class="text-right">Received</th><th class="text-right">Pending</th><th>Status</th><th>Journal</th></tr></thead><tbody><?php foreach($rows as $r): $pending=$r['status']==='REVERSED'?0:max(0,floatval($r['commission_amount'])-floatval($r['received_amount'])); ?><tr><td><?= formatDate($r['approval_date']) ?></td><td><a class="text-bold" href="../cars/loan_commission.php?car_id=<?= urlencode($r['car_id']) ?>"><?= clean(formatRegistrationNo($r['registration_no'])) ?></a><div class="table-secondary"><?= clean($r['buyer_name']) ?> · <?= clean(str_replace('_',' ',$r['ownership_type'])) ?></div></td><td><?= clean($r['financier_name']) ?><div class="table-secondary"><?= clean($r['loan_account_no']?:'-') ?></div></td><td class="text-right amount"><?= formatAmount($r['loan_amount']) ?></td><td class="text-right amount flow-in"><?= formatAmount($r['commission_amount']) ?></td><td class="text-right amount"><?= formatAmount($r['received_amount']) ?></td><td class="text-right amount flow-out"><?= formatAmount($pending) ?></td><td><span class="badge <?= $r['status']==='RECEIVED'?'badge-green':($r['status']==='REVERSED'?'badge-red':'badge-yellow') ?>"><?= clean($r['status']) ?></span></td><td><a href="../transactions/view.php?id=<?= urlencode($r['accrual_entry_id']) ?>"><?= clean($r['reference_no']) ?></a></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="9" class="text-center text-muted" style="padding:30px">No loan commission cases match these filters.</td></tr><?php endif; ?></tbody></table></div>
<?php require_once __DIR__.'/../includes/footer.php'; ?>
