<?php
$pageTitle='Outside Cars Report';$pageIcon='<i class="ri-bar-chart-box-line"></i>';
require_once __DIR__.'/../includes/header.php';require_once __DIR__.'/../includes/accounting_engine.php';
$businessId=Auth::user('business_id');Auth::requireBookAccess('outside_cars','read');$engine=new AccountingEngine($businessId,Auth::user('user_id'));
$search=trim((string)get('q',''));$buyerFilter=strtoupper(trim((string)get('buyer_status','')));$settlementFilter=strtoupper(trim((string)get('settlement_status','')));$rtoFilter=strtoupper(trim((string)get('rto_status','')));
$rows=$db->fetchAll("SELECT c.id,c.registration_no,c.make,c.model,se.display_name source_name,ocd.physical_status,ocd.buyer_status,ocd.rto_status,ocd.settlement_status,ocd.agreement_status,ocd.source_base_value,
ocs.vehicle_sale_price,ocs.separate_commission,ocs.buyer_total,ocs.buyer_outstanding,
COALESCE(ex.actual,0) actual_expenses,COALESCE(ex.approved,0) approved_expenses,
os.exact_margin,os.tiranga_share,os.tiranga_income,os.tiranga_entitlement,os.remaining_entity_payable,os.remaining_entity_receivable,
COALESCE(r.received,0)+COALESCE(r.allocated,0)+COALESCE(ocs.buyer_rto_charge,0)-COALESCE(r.paid,0) rto_clearing,
COALESCE(lc.earned,0) loan_commission,COALESCE(lc.received,0) loan_commission_received,
(SELECT COUNT(*) FROM outside_car_agreements a WHERE a.business_id=c.business_id AND a.car_id=c.id) agreement_versions,
(SELECT COUNT(*) FROM outside_car_deliveries d WHERE d.business_id=c.business_id AND d.car_id=c.id) delivered
FROM cars c JOIN outside_car_deals ocd ON ocd.business_id=c.business_id AND ocd.car_id=c.id JOIN source_entities se ON se.business_id=c.business_id AND se.id=ocd.source_entity_id
LEFT JOIN outside_car_sales ocs ON ocs.business_id=c.business_id AND ocs.car_id=c.id AND ocs.status<>'REVERSED'
LEFT JOIN outside_car_settlements os ON os.business_id=c.business_id AND os.car_id=c.id AND os.status<>'REVERSED'
LEFT JOIN (SELECT business_id,car_id,SUM(actual_amount) actual,SUM(approved_recoverable_amount) approved FROM outside_car_expenses WHERE status='POSTED' GROUP BY business_id,car_id) ex ON ex.business_id=c.business_id AND ex.car_id=c.id
LEFT JOIN (SELECT business_id,car_id,SUM(CASE WHEN movement_type='RECEIVE' AND status='POSTED' THEN amount ELSE 0 END) received,SUM(CASE WHEN movement_type='ALLOCATE' AND status='POSTED' THEN amount ELSE 0 END) allocated,SUM(CASE WHEN movement_type='PAY' AND status='POSTED' THEN amount ELSE 0 END) paid FROM outside_car_rto_movements GROUP BY business_id,car_id) r ON r.business_id=c.business_id AND r.car_id=c.id
LEFT JOIN (SELECT business_id,car_id,SUM(CASE WHEN status<>'REVERSED' THEN commission_amount ELSE 0 END) earned,SUM(CASE WHEN status<>'REVERSED' THEN received_amount ELSE 0 END) received FROM car_loan_commissions GROUP BY business_id,car_id) lc ON lc.business_id=c.business_id AND lc.car_id=c.id
WHERE c.business_id=? AND c.ownership_type='OUTSIDE' ORDER BY c.created_at DESC",[$businessId]);
$rows=array_values(array_filter($rows,function($r)use($search,$buyerFilter,$settlementFilter,$rtoFilter){$haystack=strtolower(implode(' ',[$r['registration_no'],$r['make'],$r['model'],$r['source_name']]));return($search===''||str_contains($haystack,strtolower($search)))&&($buyerFilter===''||$r['buyer_status']===$buyerFilter)&&($settlementFilter===''||$r['settlement_status']===$settlementFilter)&&($rtoFilter===''||$r['rto_status']===$rtoFilter);}));
$total=fn($key)=>array_sum(array_map(fn($r)=>floatval($r[$key]??0),$rows));
?>
<div class="page-header"><div><h1><i class="ri-bar-chart-box-line"></i> Outside Cars Report</h1><p class="page-subtitle">Journal-derived operational, outstanding, settlement, RTO, agreement, and delivery positions.</p></div><button onclick="printPage()" class="btn btn-outline"><i class="ri-printer-line"></i> Print</button></div>
<div class="filter-bar"><form method="get"><div><label class="form-label">Car or Source Entity</label><input type="search" name="q" class="form-control" value="<?= clean($search) ?>" placeholder="Registration, make, model, entity"></div><div><label class="form-label">Buyer</label><select name="buyer_status" class="form-control"><option value="">All</option><?php foreach(['NO_BUYER','PARTLY_PAID','FULLY_PAID','REFUNDED'] as $value): ?><option value="<?= $value ?>" <?= $buyerFilter===$value?'selected':'' ?>><?= clean(ucwords(strtolower(str_replace('_',' ',$value)))) ?></option><?php endforeach; ?></select></div><div><label class="form-label">Settlement</label><select name="settlement_status" class="form-control"><option value="">All</option><?php foreach(['CALCULATION_PENDING','ADVANCE_PAID','SETTLEMENT_APPROVED','PARTLY_SETTLED','FULLY_SETTLED'] as $value): ?><option value="<?= $value ?>" <?= $settlementFilter===$value?'selected':'' ?>><?= clean(ucwords(strtolower(str_replace('_',' ',$value)))) ?></option><?php endforeach; ?></select></div><div><label class="form-label">RTO</label><select name="rto_status" class="form-control"><option value="">All</option><?php foreach(['NOT_STARTED','IN_PROGRESS','COMPLETED'] as $value): ?><option value="<?= $value ?>" <?= $rtoFilter===$value?'selected':'' ?>><?= clean(ucwords(strtolower(str_replace('_',' ',$value)))) ?></option><?php endforeach; ?></select></div><button class="btn btn-outline btn-sm"><i class="ri-filter-line"></i> Apply</button><?php if($search!==''||$buyerFilter!==''||$settlementFilter!==''||$rtoFilter!==''): ?><a class="btn btn-ghost btn-sm" href="outside_cars.php">Clear all</a><?php endif; ?></form></div>
<div class="stats-grid"><div class="stat-card"><div class="stat-value"><?= count($rows) ?></div><div class="stat-label">Outside Cars</div></div><div class="stat-card"><div class="stat-value flow-out"><?= formatAmount($total('buyer_outstanding')) ?></div><div class="stat-label">Buyer Outstanding</div></div><div class="stat-card"><div class="stat-value flow-out"><?= formatAmount($total('remaining_entity_payable')) ?></div><div class="stat-label">Entity Payable</div></div><div class="stat-card"><div class="stat-value flow-in"><?= formatAmount($total('tiranga_income')) ?></div><div class="stat-label">Deal Income</div></div><div class="stat-card"><div class="stat-value flow-in"><?= formatAmount($total('loan_commission')) ?></div><div class="stat-label">Separate Loan Commission</div></div><div class="stat-card"><div class="stat-value"><?= formatAmount($total('rto_clearing')) ?></div><div class="stat-label">RTO Clearing</div></div></div>
<div class="table-container table-container-fill"><table><thead><tr><th>Car / Entity</th><th>A / B2 / C / K</th><th>Buyer</th><th>Settlement</th><th>Loan Commission</th><th>RTO</th><th>Agreement / Delivery</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><a class="text-bold" href="../outside-cars/view.php?id=<?= urlencode($r['id']) ?>"><?= clean(formatRegistrationNo($r['registration_no'])) ?></a><div class="table-secondary"><?= clean($r['source_name']) ?></div></td><td><div>A <?= formatAmount($r['source_base_value']) ?></div><div>B2 <?= formatAmount($r['approved_expenses']) ?></div><div>C <?= $r['vehicle_sale_price']!==null?formatAmount($r['vehicle_sale_price']):'-' ?></div><div>K <?= formatAmount($r['separate_commission']) ?></div></td><td><div>Total <?= formatAmount($r['buyer_total']) ?></div><div class="flow-out">Due <?= formatAmount($r['buyer_outstanding']) ?></div><span class="badge badge-blue"><?= clean(str_replace('_',' ',$r['buyer_status'])) ?></span></td><td><div>Income <?= formatAmount($r['tiranga_income']) ?></div><div>Entitlement <?= formatAmount($r['tiranga_entitlement']) ?></div><div class="flow-out">Entity due <?= formatAmount($r['remaining_entity_payable']) ?></div><div class="flow-in">Entity receivable <?= formatAmount($r['remaining_entity_receivable']) ?></div></td><td><div>Earned <?= formatAmount($r['loan_commission']) ?></div><div>Received <?= formatAmount($r['loan_commission_received']) ?></div></td><td><?= formatAmount($r['rto_clearing']) ?><div class="table-secondary"><?= clean(str_replace('_',' ',$r['rto_status'])) ?></div></td><td><span class="badge badge-blue"><?= clean(str_replace('_',' ',$r['agreement_status'])) ?></span><div><?= (int)$r['agreement_versions'] ?> version(s) · <?= $r['delivered']?'Delivered':'Not delivered' ?></div></td></tr><?php endforeach; ?></tbody></table></div>
<?php require_once __DIR__.'/../includes/footer.php'; ?>
